use master
go
CREATE DATABASE A1 ON (FILENAME = N'D:\SQL2008R2\A1.mdf')
FOR ATTACH_REBUILD_LOG;

use master
go
CREATE DATABASE EvolutionCommon ON (FILENAME = N'D:\SQL2008R2\Evolutioncommon.mdf')
FOR ATTACH_REBUILD_LOG;

use master
go
CREATE DATABASE FATS ON (FILENAME = N'D:\SQL2008R2\FATS.mdf')
FOR ATTACH_REBUILD_LOG;

use master
go
CREATE DATABASE EvolutionCommonnew ON (FILENAME = N'D:\SQL2008R2\Evolutioncommonnew.mdf')
FOR ATTACH_REBUILD_LOG;

use master
go
CREATE DATABASE [Fowarding African Transport Services] ON (FILENAME = N'D:\SQL2008R2\Fowarding African Transport Services.mdf')
FOR ATTACH_REBUILD_LOG;

use master
go
CREATE DATABASE [RITZY IT] ON (FILENAME = N'D:\SQL2008R2\RITZY IT.mdf')
FOR ATTACH_REBUILD_LOG;

use master
go
CREATE DATABASE Bfor ON (FILENAME = N'D:\SQL2014\Bfor.mdf')
FOR ATTACH_REBUILD_LOG;

use master
go
CREATE DATABASE [Cooper Tyres] ON (FILENAME = N'D:\SQL2014\Cooper Tyres.mdf')
FOR ATTACH_REBUILD_LOG;

use master
go
CREATE DATABASE EvolutionCommon ON (FILENAME = N'D:\SQL2014\EvolutionCommon.mdf')
FOR ATTACH_REBUILD_LOG;

use master
go
CREATE DATABASE EvolutionCommonVal ON (FILENAME = N'D:\SQL2014\EvolutionCommonVal.mdf')
FOR ATTACH_REBUILD_LOG;

use master
go
CREATE DATABASE Val2015 ON (FILENAME = N'D:\SQL2014\Val2015.mdf')
FOR ATTACH_REBUILD_LOG;

use master
go
CREATE DATABASE EvolutionCommon ON (FILENAME = N'D:\SQL2012\EvolutionCommon.mdf')
FOR ATTACH_REBUILD_LOG;

use master
go
CREATE DATABASE KLOM_OLD ON (FILENAME = N'D:\SQL2012\KLOM_OLD.mdf')
FOR ATTACH_REBUILD_LOG;

use master
go
CREATE DATABASE KLOM2016 ON (FILENAME = N'D:\SQL2012\KLOM2016.mdf')
FOR ATTACH_REBUILD_LOG;

use master
go
CREATE DATABASE KLOM2016_new ON (FILENAME = N'D:\SQL2012\KLOM2016_new.mdf')
FOR ATTACH_REBUILD_LOG;
